### Create a report

POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "toyota",
    "model": "corolla",
    "mileage": 50000,
    "year": 1990,
    "lng": 0,
    "lat": 0,
    "price": 500000 
}

### approve a report
PATCH http://localhost:3000/reports/29
Content-Type: application/json

{
    "approved": true
}

### get report

GET http://locahost:3000/reports?make=toyota&model=corolla